version: '3'
services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - backend