mutation createOrder($input: CreateOrderInput!) {
    createOrder(input: $input) {
        _id
        title
        description
        products {
            _id
        }
        createdAt
        updatedAt
    }
}
mutation updateOrder($orderId: ID!, $input: UpdateOrderInput!) {
    updateOrder(orderId: $orderId, input: $input) {
        _id
        title
    }
}

mutation deleteOrder($orderId: ID!) {
    deleteOrder(orderId: $orderId) {
        message
    }
}