query getAllOrders {
  orders {
    _id
    title
    description
    products
    createdAt
    updatedAt
  }
}

query getOrderById($orderId: ID!) {
  order(orderId: $orderId) {
    _id
    title
    description
    products
    createdAt
    updatedAt
  }
}