query getAuthUser {
  authUser {
    email,
    fullName,
  }
}

query getUsers {
  users {
    _id
    email,
    fullName,
    createdAt
    updatedAt

  }
}
query getUserById($userId: ID!) {
  user(userId: $userId) {
      _id,
    email,
    fullName,
    createdAt
    updatedAt
  }
}

