mutation createProduct($input: CreateProductInput!) {
    createProduct(input: $input) {
        _id
        guarantee {
            end
            start
        }
        isUsed
        order
        photo
        price {
            isDefault
            symbol
            value
        }
        serialNumber
        specification
        title
        type
        createdAt
        updatedAt
    }
}


mutation updateProduct($productId: ID!, $input: UpdateProductInput!) {
    updateProduct(productId: $productId, input: $input) {
        _id
        guarantee {
            end
            start
        }
        isUsed
        order
        photo
        price {
            isDefault
            symbol
            value
        }
        serialNumber
        specification
        title
        type
        createdAt
        updatedAt
    }
}

mutation deleteProduct($productId: ID!) {
    deleteProduct(productId: $productId) {
      message
    }
}