query getAllProducts {
  products {
    _id
    title
    serialNumber
    isUsed
    order
    photo
    guarantee {
      end
      start
    }
    price {
      isDefault
      symbol
      value
    }
    specification
    type
    createdAt
    updatedAt
  }
}

query getProductById($productId: ID!) {
  product(productId: $productId) {
    _id
    title
    serialNumber
    isUsed
    order
    photo
    guarantee {
      end
      start
    }
    price {
      isDefault
      symbol
      value
    }
    specification
    type
    createdAt
    updatedAt
  }
}

query getProductsByOrderId($orderId: ID!) {
  productsByOrderId(orderId: $orderId) {
    _id
    title
    serialNumber
    isUsed
    order
    photo
    guarantee {
      end
      start
    }
    price {
      isDefault
      symbol
      value
    }
    specification
    type
    createdAt
    updatedAt
  }
}


